version: "3.8"

networks:
  localstack-net:
    driver: bridge

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # Edge port
      - "4510-4559:4510-4559"  # Service ports
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway,cloudformation,iam,sts,logs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
    networks:
      - localstack-net

volumes:
  localstack_data:
    driver: local
